{% set name = "pyasdf" %}
{% set version = "0.3.0" %}
{% set sha256 = "ba36127e94ae24772ddfb7c9465b85dea8cb6660d39813744cb50175b421f302" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - obspy
    - colorama
    - h5py
    - dill
    - prov

test:
  imports:
    - pyasdf
  requires:
    - pytest
  commands:
    - python -m pyasdf.tests

about:
  home: https://seismicdata.github.io/pyasdf/index.html
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python module for working with ASDF files.'
  description: |
    Python module for the Adaptable Seismic Data Format (ASDF).

    For further information and contact information please see these two web sites:

    * Landing page of the ASDF data format: http://seismic-data.org
    * Github repository of pyasdf: http://www.github.com/SeismicData/pyasdf
  doc_url: https://seismicdata.github.io/pyasdf/index.html
  dev_url: https://github.com/SeismicData/pyasdf

extra:
  recipe-maintainers:
    - krischer
