{% set name = "pyasdf" %}
{% set version = "0.8.2" %}
{% set sha256 = "c33ebe6843b6b0553bd6dc2e2511c67765fd875fb3af4c4e11f537ee0c16facd" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - obspy
    - colorama
    - h5py
    - dill
    - prov

test:
  imports:
    - pyasdf
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -m pyasdf.tests

about:
  home: https://seismicdata.github.io/pyasdf/index.html
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python module for working with ASDF files.
  description: |
    Python module for the Adaptable Seismic Data Format (ASDF).

    For further information and contact information please see these two web sites:

    * Landing page of the ASDF data format: http://seismic-data.org
    * Github repository of pyasdf: http://www.github.com/SeismicData/pyasdf
  doc_url: https://seismicdata.github.io/pyasdf/index.html
  dev_url: https://github.com/SeismicData/pyasdf

extra:
  recipe-maintainers:
    - krischer
