{% set name = "pyasdf" %}
{% set version = "0.7.0" %}
{% set sha256 = "a2e02a5df8433ae392531c1afee6d677b66cd50002612595b3be32165c27b81f" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - obspy
    - colorama
    - h5py
    - dill
    - prov

test:
  imports:
    - pyasdf
  requires:
    - pytest
  commands:
    - python -m pyasdf.tests

about:
  home: https://seismicdata.github.io/pyasdf/index.html
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Python module for working with ASDF files.'
  description: |
    Python module for the Adaptable Seismic Data Format (ASDF).

    For further information and contact information please see these two web sites:

    * Landing page of the ASDF data format: http://seismic-data.org
    * Github repository of pyasdf: http://www.github.com/SeismicData/pyasdf
  doc_url: https://seismicdata.github.io/pyasdf/index.html
  dev_url: https://github.com/SeismicData/pyasdf

extra:
  recipe-maintainers:
    - krischer
