travis:
  secure:
    BINSTAR_TOKEN: YB5K1D0d5EtOk5leK9Yg+Juy6bVbUKuVGp0ITLiIRRK7T34RCbea7990jPes4OInB4e5iNLTg+LXyBD2yTsKhzhYRLs8c9bZ5rUxY/CMM8RNSyPUIKAHqZEBL6L4vlJ/CehZPVlm8193Si4VCD5s+eZjDTc+QO+VB9oOHOBAQPzbEtj6sreRSQUZBO2Ch5mG5Lp3v5gF0ld4NfBokI1SIpDSEUM/S7JamKKcseXr5E4SEH43GLiY2cVjizBKXRH0moOtOzSl5/VnBZKVOwotbTErWQY8ToZA1TszVDZhvPB0tOkE4/ScT3rOUpP8Y/JB0gSJKFGEjHKHoGDFpDMmeheI9zX3x1JrtXUpKYTJ+LetjJx+p6APYv288RHpe9NYOPTxwGokmTuF6OfnGnIoA6YcJoBUI52Ol/ek03drxsbuxHM+P/VOFQa+ayTirT5OXIhq4J6kIOPogWQAf9tEtDrONXlyBSByuMgLgwQh7QsBQPtkvcaInp/1y5vhx2BvGdNs0NXijFVf5ZnYHUawVfSpUM1xrWEfabCUR5g2uqT1LFi8J6iqFO3fDw37dBXP7VVhysp11XEdhogtxxjPlly03qzsKdxOhaPgX7hxs94MBweV9P4CJni9S85FLVqZQnfcDBwINKpGhpXb6GVtowtCAGlg/Kh/rBbGLAcHXaY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
