travis:
  secure:
    BINSTAR_TOKEN: N893YMbMzXlvyk+vkrvANUHrIDNhozEvxyQwYLO7mz+YzuF11UaTokBxAjDmY+4qWA0ZHKXmx8u8AKRHnV6As5MoJBU4etXFq0NUJZV2G4xIg2rv+7Cw1qj0vWwKtpoMWUaT9ueeLJCc9cUyorevWMBfNHauq5y3am6z1M0cCXQs+I7zEnpz1ZXTmYSs/bAUBFC6ExMjareqXPAFbVpIdEBJr/XUYf6KG16jbR6jDQjefTcFALK9hQwpJQcDeyL5uGeopmhuJWgkkt/SxTl/c2GIA6M7tgmeGYSrowBej+vW46NZ2U+ouu8I+zazR7m69Tjbh8OzaazUta9UGmdmmH8+V5R+TFjUlOmuMIx8lsq1ZSY3JFILYo7R+UK3m6/e4RgMbFi9RKGu4xyPsQGw47b9MGqcLVrO7vNziWd0IQB2yDDgZb5UKQAeJnAi42g8Jv/m5m776+xOThvsbODIXJvbDmcyh5ikNyfrlgY6odm2PSs+SLoIYlsiPmn0g46jzzBDdVHsORaJpNrq0sT9Oe3Qs640SkcR/D1RSzqp/1ZCo9I+P/wkoGWQxCCBQ3y+A+pZGzjdJMKsQXMAuoDdNlz/w1zg99nG24rQDsz7Wy8HHmemvn33BHZAnPqLNjioH/P9G35SpUzdBARyHW668r7VmcZ2pSMnbnm0s4DR0/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
